name: Test workflow
on: 
  workflow_dispatch:
    inputs:
      deploy-country: 
        required: true
        type: string
      deploy-environment:
        required: true
        type: string

jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        uses: midnattsol/metadata@main
        with: 
          country: ${{ inputs.deploy-country }}
          environment: ${{ inputs.deploy-environment }}
          metadata: ${{ join(github.event.repository.topics, ' ') }}
      - name: Testing var
        run: |
          echo "Account: $AWS_ACCOUNT_ID"
          echo "Region: $AWS_REGION"
          echo "Topics: ${{ join(github.event.repository.topics, ' ') }}"